### ISSUE TITLE
How can I troubleshoot plugin failures?

### ISSUE THREAD

**Issue by steve-marmalade** [cloudnative-pg/plugin-barman-cloud#165]
Hi team, getting starting with cloudnative-pg and figured I'd jump straight to the new `standard` images with `plugin-barman-cloud`.

I am struggling to get WAL Archiving and Backups working properly with my object store (GCS) and could use some advice on how to troubleshoot.

# Setup

My first step was to update everything to the latest development versions, in case any fixes are already in `main`.

```bash
$ kubectl get deployment -o yaml -n cnpg-system cnpg-controller-manager   | grep ghcr.io/cloudnative-pg/cloudnative-pg
          value: ghcr.io/cloudnative-pg/cloudnative-pg-testing:main
        image: ghcr.io/cloudnative-pg/cloudnative-pg-testing:main
```

```bash
$ cmctl check api
The cert-manager API is ready
```

```yaml
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: gcs-store
spec:
  configuration:
    destinationPath: gcs://my-bucket/cnpg/
    googleCredentials:
      applicationCredentials:
        name: backup-creds
        key: gcsCredentials
    wal:
      compression: gzip
```

```bash
$ kubectl describe secrets/backup-creds
Name:         backup-creds
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
gcsCredentials:  2352 bytes
```

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-test-cluster
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql-testing:17.4-202502241404-standard-bookworm
  instances: 1
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: gcs-store
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
```

# WAL Archiving

```bash
$ kubectl logs pg-test-cluster-1

{"level":"error","ts":"2025-02-25T19:18:00.524302702Z","logger":"wal-archive","msg":"Error while calling ArchiveWAL, failing","pluginName":"barman-cloud.cloudnative-pg.io","logging_pod":"pg-test-cluster-1","error":"rpc error: code = Unknown desc = unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20250102082645-95c37fe624d0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cnpi/plugin/client.(*data).ArchiveWAL\n\tinternal/cnpi/plugin/client/wal.go:66\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.archiveWALViaPlugins\n\tpkg/management/postgres/archiver/archiver.go:301\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.internalRun\n\tpkg/management/postgres/archiver/archiver.go:154\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres/archiver.Run\n\tpkg/management/postgres/archiver/archiver.go:139\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:62\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071\nmain.main\n\tcmd/manager/main.go:68\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.0/x64/src/runtime/proc.go:283"}
{"level":"error","ts":"2025-02-25T19:18:00.524572122Z","logger":"wal-archive","msg":"failed to run wal-archive command","logging_pod":"pg-test-cluster-1","error":"rpc error: code = Unknown desc = unexpected failure invoking barman-cloud-wal-archive: exit status 4","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\tpkg/mod/github.com/cloudnative-pg/machinery@v0.0.0-20250102082645-95c37fe624d0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/walarchive.NewCmd.func1\n\tinternal/cmd/manager/walarchive/cmd.go:67\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071\nmain.main\n\tcmd/manager/main.go:68\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.0/x64/src/runtime/proc.go:283"}
{"level":"info","ts":"2025-02-25T19:18:00.526451995Z","logger":"postgres","msg":"record","logging_pod":"pg-test-cluster-1","record":{"log_time":"2025-02-25 19:18:00.526 UTC","process_id":"46","session_id":"67be1407.2e","session_line_num":"59","session_start_time":"2025-02-25 19:03:35 UTC","transaction_id":"0","error_severity":"LOG","sql_state_code":"00000","message":"archive command failed with exit code 1","detail":"The failed archive command was: /controller/manager wal-archive --log-destination /controller/log/postgres.json pg_wal/000000010000000000000001","backend_type":"archiver","query_id":"0"}}
{"level":"info","ts":"2025-02-25T19:18:00.526476227Z","logger":"postgres","msg":"record","logging_pod":"pg-test-cluster-1","record":{"log_time":"2025-02-25 19:18:00.526 UTC","process_id":"46","session_id":"67be1407.2e","session_line_num":"60","session_start_time":"2025-02-25 19:03:35 UTC","transaction_id":"0","error_severity":"WARNING","sql_state_code":"01000","message":"archiving write-ahead log file \"000000010000000000000001\" failed too many times, will try again later","backend_type":"archiver","query_id":"0"}}
```

# Backups

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-test-cluster-backup-example
spec:
  method: plugin
  cluster:
    name: pg-test-cluster
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: gcs-store
```

```
$ kubectl describe backup/pg-test-cluster-backup-example
Name:         pg-test-cluster-backup-example
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2025-02-25T19:20:01Z
  Generation:          1
  Resource Version:    47624
  UID:                 42707bf1-d08f-42cc-9c2e-39d6427a3cbb
Spec:
  Cluster:
    Name:  pg-test-cluster
  Method:  plugin
  Plugin Configuration:
    Name:  barman-cloud.cloudnative-pg.io
    Parameters:
      Barman Object Name:  gcs-store
Status:
  Error:  rpc error: code = Unknown desc = exit status 4
  Instance ID:
    Container ID:  containerd://94dda2e1fe5b73cba5bd2e5abc6c59f81fcec71fee11e61066effe0a3225a159
    Pod Name:      pg-test-cluster-1
  Method:          plugin
  Phase:           failed
Events:
  Type    Reason    Age   From                   Message
  ----    ------    ----  ----                   -------
  Normal  Starting  13s   cloudnative-pg-backup  Starting backup for cluster pg-test-cluster
  Normal  Starting  13s   local-webserver        Backup started
  Normal  Failed    12s   local-webserver        Backup failed
```
