### ISSUE TITLE
Replica cluster fails to create instance with duplicate-path error

### ISSUE THREAD

**Issue by mnencia** [cloudnative-pg/plugin-barman-cloud#329]
cluster.yaml

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-replica
spec:
  instances: 3
  imagePullPolicy: Always
  bootstrap:
    recovery:
      source: source
  replica:
    enabled: true
    source: source
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-store
        serverName: cluster-example
  storage:
    size: 1Gi
```

minio-store.yaml

```yaml
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-store
spec:
  retentionPolicy: 1d
  instanceSidecarConfiguration:
    retentionPolicyIntervalSeconds: 30
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  configuration:
    destinationPath: s3://backups/
    endpointURL: https://minio:9000
    endpointCA:
      key: ca.crt
      name: my-minio-server-cert
    s3Credentials:
      accessKeyId:
        name: minio
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: minio
        key: ACCESS_SECRET_KEY
    wal:
      compression: zstd
    data:
      immediateCheckpoint: true
```

Relevant log in plugin-barman-cloud: 

```json
{
  "level": "info",
  "ts": "2025-05-08T13:41:57.390288172Z",
  "logger": "lifecycle",
  "msg": "Lifecycle hook reconciliation start"
}
{
  "level": "info",
  "ts": "2025-05-08T13:41:57.390620701Z",
  "logger": "lifecycle",
  "msg": "Reconciling job"
}
{
  "level": "debug",
  "ts": "2025-05-08T13:41:57.390855955Z",
  "logger": "plugin-barman-cloud-lifecycle",
  "msg": "starting job reconciliation",
  "jobName": "cluster-replica-1-full-recovery",
  "caller": "/workspace/internal/cnpgi/operator/lifecycle.go:168"
}
{
  "level": "debug",
  "ts": "2025-05-08T13:41:57.391299995Z",
  "logger": "plugin-barman-cloud-lifecycle",
  "msg": "generated patch",
  "jobName": "cluster-replica-1-full-recovery",
  "caller": "/workspace/internal/cnpgi/operator/lifecycle.go:196",
  "content": "[{\"op\":\"add\",\"path\":\"/spec/template/spec/volumes/3\",\"value\":{\"name\":\"plugins\",\"emptyDir\":{}}},{\"op\":\"add\",\"path\":\"/spec/template/spec/volumes/4\",\"value\":{\"name\":\"barman-certificates\",\"projected\":{\"sources\":[{\"secret\":{\"name\":\"my-minio-server-cert\",\"items\":[{\"key\":\"ca.crt\",\"path\":\"minio-store/barman-ca.crt\"}]}},{\"secret\":{\"name\":\"my-minio-server-cert\",\"items\":[{\"key\":\"ca.crt\",\"path\":\"minio-store/barman-ca.crt\"}]}}]}}},{\"op\":\"add\",\"path\":\"/spec/template/spec/initContainers/1\",\"value\":{\"name\":\"plugin-barman-cloud\",\"image\":\"registry.dev:5000/plugin-barman-cloud-sidecar:latest\",\"args\":[\"restore\"],\"env\":[{\"name\":\"PGDATA\",\"value\":\"/var/lib/postgresql/data/pgdata\"},{\"name\":\"POD_NAME\",\"value\":\"cluster-replica-1-full-recovery\"},{\"name\":\"NAMESPACE\",\"value\":\"default\"},{\"name\":\"CLUSTER_NAME\",\"value\":\"cluster-replica\"},{\"name\":\"PSQL_HISTORY\",\"value\":\"/controller/tmp/.psql_history\"},{\"name\":\"PGPORT\",\"value\":\"5432\"},{\"name\":\"PGHOST\",\"value\":\"/controller/run\"},{\"name\":\"TMPDIR\",\"value\":\"/controller/tmp\"},{\"name\":\"CNPG_STANDBY_TCP_USER_TIMEOUT\",\"value\":\"5000\"},{\"name\":\"SPOOL_DIRECTORY\",\"value\":\"/controller/wal-restore-spool\"},{\"name\":\"CUSTOM_CNPG_GROUP\",\"value\":\"postgresql.cnpg.io\"},{\"name\":\"CUSTOM_CNPG_VERSION\",\"value\":\"v1\"}],\"resources\":{},\"restartPolicy\":\"Always\",\"volumeMounts\":[{\"name\":\"barman-certificates\",\"mountPath\":\"/barman-certificates\"},{\"name\":\"pgdata\",\"mountPath\":\"/var/lib/postgresql/data\"},{\"name\":\"scratch-data\",\"mountPath\":\"/run\"},{\"name\":\"scratch-data\",\"mountPath\":\"/controller\"},{\"name\":\"shm\",\"mountPath\":\"/dev/shm\"},{\"name\":\"plugins\",\"mountPath\":\"/plugins\"}],\"startupProbe\":{\"exec\":{\"command\":[\"/manager\",\"healthcheck\",\"unix\"]},\"timeoutSeconds\":10,\"failureThreshold\":10},\"imagePullPolicy\":\"Always\",\"securityContext\":{\"capabilities\":{\"drop\":[\"ALL\"]},\"privileged\":false,\"runAsNonRoot\":true,\"readOnlyRootFilesystem\":true,\"allowPrivilegeEscalation\":false,\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}}},{\"op\":\"add\",\"path\":\"/spec/template/spec/containers/0/volumeMounts/4\",\"value\":{\"name\":\"plugins\",\"mountPath\":\"/plugins\"}}]"
}
```

Relevant logs in CNPG:

```json
{
  "level": "info",
  "ts": "2025-05-08T13:41:57.389640071Z",
  "msg": "Creating new Job",
  "controller": "cluster",
  "controllerGroup": "postgresql.cnpg.io",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "cluster-replica",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "cluster-replica",
  "reconcileID": "b2ffe527-c888-4140-8e85-461f79e7d7f9",
  "jobName": "cluster-replica-1-full-recovery",
  "primary": true
}
{
  "level": "error",
  "ts": "2025-05-08T13:41:57.434442707Z",
  "msg": "Unable to create job",
  "controller": "cluster",
  "controllerGroup": "postgresql.cnpg.io",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "cluster-replica",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "cluster-replica",
  "reconcileID": "b2ffe527-c888-4140-8e85-461f79e7d7f9",
  "job": {
    "apiVersion": "batch/v1",
    "kind": "Job",
    "namespace": "default",
    "name": "cluster-replica-1-full-recovery"
  },
  "error": "Job.batch \"cluster-replica-1-full-recovery\" is invalid: [spec.template.spec.volumes[4].projected: Invalid value: \"my-minio-server-cert\": conflicting duplicate paths, spec.template.spec.initContainers[1].volumeMounts[0].name: Not found: \"barman-certificates\"]",
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ClusterReconciler).createPrimaryInstance\n\tinternal/controller/cluster_create.go:1190\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ClusterReconciler).reconcilePods\n\tinternal/controller/cluster_controller.go:928\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ClusterReconciler).reconcileResources\n\tinternal/controller/cluster_controller.go:757\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ClusterReconciler).reconcile\n\tinternal/controller/cluster_controller.go:520\ngithub.com/cloudnative-pg/cloudnative-pg/internal/controller.(*ClusterReconciler).Reconcile\n\tinternal/controller/cluster_controller.go:220\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"
}
{
  "level": "debug",
  "ts": "2025-05-08T13:41:57.434568512Z",
  "msg": "Reconciliation loop end",
  "controller": "cluster",
  "controllerGroup": "postgresql.cnpg.io",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "cluster-replica",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "cluster-replica",
  "reconcileID": "b2ffe527-c888-4140-8e85-461f79e7d7f9",
  "caller": "internal/controller/cluster_controller.go:154"
}
{
  "level": "error",
  "ts": "2025-05-08T13:41:57.43461492Z",
  "msg": "Reconciler error",
  "controller": "cluster",
  "controllerGroup": "postgresql.cnpg.io",
  "controllerKind": "Cluster",
  "Cluster": {
    "name": "cluster-replica",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "cluster-replica",
  "reconcileID": "b2ffe527-c888-4140-8e85-461f79e7d7f9",
  "error": "Job.batch \"cluster-replica-1-full-recovery\" is invalid: [spec.template.spec.volumes[4].projected: Invalid value: \"my-minio-server-cert\": conflicting duplicate paths, spec.template.spec.initContainers[1].volumeMounts[0].name: Not found: \"barman-certificates\"]",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:347\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/Users/mnencia/.asdf/installs/golang/1.24.3/packages/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255"
}
```
