### ISSUE TITLE
[Feature]: verify barmanObjectName

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/plugin-barman-cloud#337]
when referencing an `barmanObjectName ` in `externalCluster` that is used for recovery
and that does not exist
the creation of the cluster stops without error after "creating cluster role" phase

Therefor it would be good to verify the if the barmanObjectName exists

```
...
  bootstrap:
#########################
# restore just in case...
#########################

    recovery:
      source: source    
#      recoveryTarget:
#        targetTime: "2023-06-19 17:15:00.00000+02"

  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        # Recovery Object Store (pull, read-only)
        barmanObjectName: minio-store
        serverName: xxx
...
```
