### ISSUE TITLE
`k cnpg backup $cluster` fails after plugin migration: "cannot proceed with the backup as the cluster has no backup section"

### ISSUE THREAD

**Issue by hwo-wd** [cloudnative-pg/plugin-barman-cloud#353]
I've just followed the migration guide on a test cluster, and <https://cloudnative-pg.io/plugin-barman-cloud/docs/migration/#step-2-update-the-cluster-for-plugin-wal-archiving> is stating:

> Remove the entire spec.backup section if it is now empty

This was the case for me. From a migration perspective, things went fine (except that the ["no downtime" migration in fact restarts the cluster](https://github.com/cloudnative-pg/plugin-barman-cloud/issues/348)), but now `kubectl cnpg backup harbor-db` fails with a reasonable `cannot proceed with the backup as the cluster has no backup section`:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  creationTimestamp: "2025-05-26T13:54:29Z"
  generation: 1
  labels:
    cnpg.io/cluster: harbor-db
  name: harbor-db-20250526155429
  namespace: harbor
  resourceVersion: "164108864"
  uid: 4be5a44d-fe3a-492b-b0c0-e1b16154f752
spec:
  cluster:
    name: harbor-db
  method: barmanObjectStore
status:
  error: cannot proceed with the backup as the cluster has no backup section
  phase: failed
```

What's the suggested way moving forward here? -- thanks

PS: `ScheduledBackup`s work like a charm, even w/ the empty `backup` stanza ;-)

Cluster:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
  name: harbor-db
  namespace: harbor
spec:
  bootstrap:
    recovery:
      owner: harbor
      source: harbor-db
  externalClusters:
  - name: harbor-db
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: netapp
        serverName: harbor-db
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: 17
    name: postgres
  instances: 3
  logLevel: info
  monitoring:
    enablePodMonitor: true
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: netapp
  postgresql:
    parameters:
      timezone: Europe/Vienna
  storage:
    size: 3Gi
```
