### ISSUE TITLE
`cnpg_collector_last_available_backup_timestamp` metric does NOT get updated when using barman-cloud plugin

### ISSUE THREAD

**Issue by hwo-wd** [cloudnative-pg/plugin-barman-cloud#380]
As per #353, I've followed the migration guide and I'm now able to create manual backups using `kubectl cnpg`;
However, I've just noticed that the metric `cnpg_collector_last_available_backup_timestamp` does not seem to get updated and thus all backup related fields ((1) `Last Base Backup` field in the `Backups` section and (2) `Backups`in the `Health` section) show red in the Grafana dashboard:

<img width="1934" alt="Image" src="https://github.com/user-attachments/assets/26852637-3054-4e50-a563-7f39ab422efe" />

The (scheduled and/or manual) backups are created though:

<img width="2389" alt="Image" src="https://github.com/user-attachments/assets/626b5b8b-baf5-45aa-891a-a72a25405eb9" />
<details>

```yaml
Name:         scheduledbackup-harbor-20250602040000
Namespace:    harbor
Labels:       cnpg.io/cluster=harbor-db
              cnpg.io/immediateBackup=false
              cnpg.io/scheduled-backup=scheduledbackup-harbor
Annotations:  <none>
API Version:  postgresql.cnpg.io/v1
Kind:         Backup
Metadata:
  Creation Timestamp:  2025-06-02T04:00:00Z
  Generation:          1
  Owner References:
    API Version:     postgresql.cnpg.io/v1
    Controller:      true
    Kind:            ScheduledBackup
    Name:            scheduledbackup-harbor
    UID:             09e764db-5b63-406c-bf4d-bbd22d1a3bc0
  Resource Version:  170252222
  UID:               80d55ffb-176b-47ee-9cde-8bdfbc973985
Spec:
  Cluster:
    Name:  harbor-db
  Method:  plugin
  Plugin Configuration:
    Name:  barman-cloud.cloudnative-pg.io
Status:
  Backup Id:    20250602T040002
  Backup Name:  backup-20250602040000
  Begin LSN:    0/B302A900
  Begin Wal:    0000000B00000000000000B3
  End LSN:      0/B5000000
  End Wal:      0000000B00000000000000B5
  Instance ID:
    Container ID:  containerd://d4d305adf34c5a019f49e05d0d82c66796f81b3594d69cd829f132408f1c16f6
    Pod Name:      harbor-db-1
  Method:          plugin
  Online:          true
  Phase:           completed
  Plugin Metadata:
    Cluster UID:   6cc84a1b-6f55-40e7-a922-15a4799fcc06
    Display Name:  BarmanCloudInstance
    Name:          barman-cloud.cloudnative-pg.io
    Plugin Name:   barman-cloud.cloudnative-pg.io
    Timeline:      11
    Version:       0.4.0
  Started At:      2025-06-02T04:00:02Z
  Stopped At:      2025-06-02T04:00:06Z
Events:            <none>
```

</details>

However, the metric itself does not get updated:

<img width="1285" alt="Image" src="https://github.com/user-attachments/assets/0e1ec0f9-284a-45ae-83ec-40ad3f738899" />

-> this is the `2025-05-26 04:00:04`: on said date I've updated all my test clusters to use the barman-cloud plugin
