### ISSUE TITLE
Failed to pull image "ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar:v0.5.0"

### ISSUE THREAD

**Issue by w-ronin** [cloudnative-pg/plugin-barman-cloud#391]
Please add a possibility to specify image path for people under a proxy.

**Comment by w-ronin** [comment]
I've found a secret `plugin-barman-cloud-gt85cmh99d`, with `SIDECAR_IMAGE` property.

And in Deployment:

```
    env:
    - name: SIDECAR_IMAGE
      valueFrom:
        secretKeyRef:
          key: SIDECAR_IMAGE
          name: plugin-barman-cloud-gt85cmh99d
```

This could be ConfigMap instead of Secret:

```
    envFrom:
    - configMapRef:
        name: plugin-barman-cloud-gt85cmh99d
```
