### ISSUE TITLE
x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD or a valid sha256 value

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/plugin-barman-cloud#393]
I'm running plugin-barman-cloud 0.5.0 and cnpg 1.26 and I'm facing this error

```
{
  "level": "info",
  "ts": "2025-06-05T08:06:43.993116246+02:00",
  "logger": "barman-cloud-wal-archive",
  "msg": "2025-06-05 08:06:43,992 [4369] ERROR: Barman cloud WAL archiver exception: An error occurred (InvalidArgument) when calling the PutObject operation: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD or a valid sha256 value.",
  "pipe": "stderr",
  "logging_pod": "plugin-1"
}
{
  "level": "info",
  "ts": "2025-06-05T08:06:44.000866388+02:00",
  "logger": "barman-cloud-wal-archive",
  "msg": "2025-06-05 08:06:44,000 [4370] ERROR: Barman cloud WAL archiver exception: An error occurred (InvalidArgument) when calling the PutObject operation: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD or a valid sha256 value.",
  "pipe": "stderr",
  "logging_pod": "plugin-1"
}
{
  "level": "error",
  "ts": "2025-06-05T08:06:44.136402813+02:00",
  "msg": "Error invoking barman-cloud-wal-archive",
  "logging_pod": "plugin-1",
  "walName": "/var/lib/postgresql/data/pgdata/pg_wal/00000004000000000000001B",
  "options": [
    "--gzip",
    "--endpoint-url",
    "https://xxx",
    "--cloud-provider",
    "aws-s3",
    "s3://xxx",
    "plugin",
    "/var/lib/postgresql/data/pgdata/pg_wal/00000004000000000000001B"
  ],
  "exitCode": -1,
  "error": "exit status 4",
  "stacktrace": "github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/go/pkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/walarchive.(*BarmanArchiver).Archive\n\t/go/pkg/mod/github.com/cloudnative-pg/barman-cloud@v0.3.1/pkg/walarchive/cmd.go:83\ngithub.com/cloudnative-pg/barman-cloud/pkg/walarchive.(*BarmanArchiver).ArchiveList.func1\n\t/go/pkg/mod/github.com/cloudnative-pg/barman-cloud@v0.3.1/pkg/walarchive/cmd.go:115"
}
{
  "level": "info",
  "ts": "2025-06-05T08:06:44.137187338+02:00",
  "msg": "Failed archiving WAL: PostgreSQL will retry",
  "logging_pod": "plugin-1",
  "walName": "/var/lib/postgresql/data/pgdata/pg_wal/00000004000000000000001B",
  "startTime": "2025-06-05T08:06:41.589246322+02:00",
  "endTime": "2025-06-05T08:06:44.136582491+02:00",
  "elapsedWalTime": 2.547336269,
  "error": "unexpected failure invoking barman-cloud-wal-archive: exit status 4"
}
```

this is the barmanObjectStore config

```
---
# ##################
# ObjectStore config
# ##################
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: plugin-c800
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: "s3://xxx"    
    endpointURL: "https://xxx"
    endpointCA:
       name: xxx-ca
       key: tls.crt     
    s3Credentials:
      accessKeyId:
        name: xxx-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: xxx-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip # bzip2;gzip;snappy
      maxParallel: 2
    data:
      compression: gzip # bzip2;gzip;snappy
      immediateCheckpoint: true  
      jobs: 2   
```
