### ISSUE TITLE
PURE Storage: A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by beauwest** [cloudnative-pg/plugin-barman-cloud#420]
Hello, we use S3-compatable storage via PURE, and the previous `.spec.backup.barmanObjectStore` worked well.

I'm attempting to upgrade to the Barman Cloud Plugin, and I'm receiving these errors
> {"level":"info","ts":"2025-06-25T18:58:25.05475805Z","logger":"barman-cloud-wal-archive","msg":"2025-06-25 18:58:25,054 [173] ERROR: Barman cloud WAL archiver exception: An error occurred (NotImplemented) when calling the PutObject operation: A header you provided implies functionality that is not implemented.","pipe":"stderr","logging_pod":"postgresql-1"}

I understand that PURE isn't directly supported, but I'm more looking to understand what changed, and if there's any solution.

The `ObjectStore` I'm using is
```yaml
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgresql-pure
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: postgresql
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://<<bucket>>/
    endpointURL: https://<<IP>>
    endpointCA:
      name: pure-objectstore
      key: certificate
    s3Credentials:
      accessKeyId:
        name: pure-objectstore
        key: key
      secretAccessKey:
        name: pure-objectstore
        key: secret
    wal:
      compression: gzip
    data:
      compression: gzip
```

Thank you!
